### ISSUE TITLE
Dependent Types

### ISSUE THREAD

**Issue by andrewthad** [Gabriel439/Haskell-Annah-Library#5]
I'm able to encode a dependent sum in annah with:

```
    \(k : *)
->  \(b : k -> *)

->  type DepSum

    data Make (_1 : k) (_2 : b _1)
    fold eliminate

    in   DepSum
```

But I cannot write a type function of type `k -> *` to actually give it an argument. Functions like

```
let func ( b1 : ./Bool ) : * =
    b1 * ./Nat ./Prod0
in  func
```

are rejected, which makes sense, given that the kind of `*` is not `*`. How can I write `func`?

**Comment by Gabriella439** [comment]
@andrewthad: `morte` (which is what `annah` is based upon) does not support universe-polymorphism, which is what would be needed to abstract over `*`

**Comment by andrewthad** [comment]
Good to know. Makes sense.
